# ----------------------- #
#      Main Configs       #
# ----------------------- #

# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

url: "http://localhost"
port: 4004
title: Equo
name: Equo
author: Make Technology
description: > # Write an awesome description for your new site here.
  Equo is a modern Java/HTML Application framework based on latest Chromium 
  embedded browser and powerful Eclipse platform. It allows to build cross 
  platform desktop apps with Java, JavaScript, HTML, and CSS.

# Site owner
owner:
  name: Make Technology
  disqus-shortname: equoblog
  twitter: 
  facebook: 
  google:
    plus: 
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: #username
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url: http://www.equo.maketechnology.io
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
highlighter: pygments

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/wemaketech
  - title: linkedin
    url: https://www.linkedin.com/company/make-technology

blog_path: /blog.html
# blog_path : /posts.html
exclude: [assets/js/bootstrap.js, assets/js/jquery-1.10.2.js, assets/js/landing-page.js, assets/css/bootstrap.css, assets/font-awesome-4.1.0/css/font-awesome.css, assets/font-awesome-4.1.0/scss, assets/font-awesome-4.1.0/less, "GemFile", "Gemfile.lock", README.md, _posts/]
